from __future__ import annotations

import csv
import json
from pathlib import Path
import shutil
import subprocess
from typing import Any, Dict, List, Tuple

from .flanker_demo import TRIAL_COLUMN_ORDER


PSYCHDS_SCHEMA_VERSION = "1.5.1"


def _json_dump(path: Path, payload: Dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=TRIAL_COLUMN_ORDER)
        writer.writeheader()
        writer.writerows(rows)


def _dataset_description(
    study_title: str,
    study_spec_reference: str,
    study_spec_sha256: str,
) -> Dict[str, Any]:
    return {
        "@context": "http://schema.org/",
        "@type": "Dataset",
        "schemaVersion": PSYCHDS_SCHEMA_VERSION,
        "name": "Flanker behavioral vertical slice synthetic demo dataset",
        "description": (
            "Deterministic synthetic trial-level dataset curated from the canonical "
            "Flanker study specification for the cogsci-skilllib behavioral demo slice."
        ),
        "license": "CC0-1.0",
        "author": [
            {
                "@type": "Organization",
                "name": "cogsci-skilllib",
            }
        ],
        "citation": (
            "Synthetic deterministic demo data generated by cogsci-skilllib for the "
            "Flanker behavioral vertical slice."
        ),
        "keywords": [
            "behavioral",
            "flanker",
            "synthetic",
            "deterministic demo",
            "Psych-DS-aligned",
        ],
        "variableMeasured": TRIAL_COLUMN_ORDER,
        "usageInfo": (
            "Source study spec: {reference}; study spec SHA-256: {digest}; study title: {title}."
        ).format(
            reference=study_spec_reference,
            digest=study_spec_sha256,
            title=study_title,
        ),
    }


def _sidecar_metadata(
    participant_id: str,
    session_id: str,
    mapping_variant: str,
) -> Dict[str, Any]:
    return {
        "@context": "http://schema.org/",
        "@type": "Dataset",
        "schemaVersion": PSYCHDS_SCHEMA_VERSION,
        "name": "Synthetic Flanker participant data file",
        "description": (
            "Deterministic synthetic trial-level Flanker data for participant "
            "{participant} session {session} using response mapping variant {mapping}."
        ).format(
            participant=participant_id,
            session=session_id,
            mapping=mapping_variant,
        ),
        "license": "CC0-1.0",
        "variableMeasured": TRIAL_COLUMN_ORDER,
    }


def write_psychds_dataset(
    psychds_dir: Path,
    study_title: str,
    study_spec_reference: str,
    study_spec_sha256: str,
    synthetic_tables: List[Dict[str, Any]],
) -> Dict[str, Any]:
    psychds_dir.mkdir(parents=True, exist_ok=True)
    data_dir = psychds_dir / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    _json_dump(
        psychds_dir / "dataset_description.json",
        _dataset_description(study_title, study_spec_reference, study_spec_sha256),
    )

    data_files: List[str] = []
    for table in synthetic_tables:
        stem = "participant-{participant}_session-{session}_data".format(
            participant=table["participant_id"],
            session=table["session_id"],
        )
        csv_path = data_dir / (stem + ".csv")
        json_path = data_dir / (stem + ".json")
        _write_csv(csv_path, table["rows"])
        _json_dump(
            json_path,
            _sidecar_metadata(
                table["participant_id"],
                table["session_id"],
                table["mapping_variant"],
            ),
        )
        data_files.append(str(csv_path.relative_to(psychds_dir)))

    return {
        "dataset_root": "psychds",
        "dataset_description": "psychds/dataset_description.json",
        "data_files": sorted(data_files),
        "schema_version": PSYCHDS_SCHEMA_VERSION,
        "alignment_note": "Psych-DS-aligned for the deterministic demo path.",
    }


def run_psychds_validator(psychds_dir: Path, mode: str) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    validate_binary = shutil.which("validate")

    if mode == "never":
        artifact = {
            "status": "not_run",
            "tool": "psychds-validator",
            "reason": "Validation disabled by --validate-psychds never.",
        }
        summary = {
            "status": "not_run",
            "tool": "psychds-validator",
            "requested_mode": mode,
            "command_available": bool(validate_binary),
        }
        return artifact, summary

    if validate_binary is None:
        if mode == "always":
            raise RuntimeError("validate command not found but --validate-psychds always was requested.")
        artifact = {
            "status": "not_run",
            "tool": "psychds-validator",
            "reason": "validate command not found on PATH.",
        }
        summary = {
            "status": "not_run",
            "tool": "psychds-validator",
            "requested_mode": mode,
            "command_available": False,
        }
        return artifact, summary

    completed = subprocess.run(
        [validate_binary, str(psychds_dir), "--json"],
        check=False,
        capture_output=True,
        text=True,
    )

    stdout = completed.stdout.strip()
    if stdout:
        try:
            artifact = json.loads(stdout)
        except json.JSONDecodeError:
            artifact = {
                "status": "error",
                "tool": "psychds-validator",
                "reason": "Validator output was not valid JSON.",
                "stdout": stdout,
                "stderr": completed.stderr.strip(),
                "returncode": completed.returncode,
            }
    else:
        artifact = {
            "status": "error",
            "tool": "psychds-validator",
            "reason": "Validator returned no JSON output.",
            "stdout": stdout,
            "stderr": completed.stderr.strip(),
            "returncode": completed.returncode,
        }

    summary = {
        "status": "passed" if completed.returncode == 0 else "failed",
        "tool": "psychds-validator",
        "requested_mode": mode,
        "command_available": True,
        "returncode": completed.returncode,
    }
    return artifact, summary
