from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "skills" / "catalog.json"
README_PATH = ROOT / "README.md"
GENERATED_PATH = ROOT / "docs" / "generated" / "skills-table.md"

START = "<!-- SKILL_TABLE_START -->"
END = "<!-- SKILL_TABLE_END -->"


def load_catalog() -> dict:
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))


def render_table(catalog: dict) -> str:
    skills = catalog["skills"]
    header = [
        "<!-- generated by scripts/render_skill_catalog.py -->",
        "",
        "| Skill | Status | Phase | Lane | Standards | Description |",
        "|---|---|---|---|---|---|",
    ]
    rows = []
    for skill in skills:
        standards = ", ".join(skill.get("standards", []))
        rows.append(
            f"| `{skill['slug']}` | {skill['status']} | {skill['phase']} | {skill['lane']} | {standards} | {skill['description']} |"
        )
    return "\n".join(header + rows) + "\n"


def update_readme(table: str) -> None:
    text = README_PATH.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise SystemExit("README markers not found.")
    before, rest = text.split(START, 1)
    middle, after = rest.split(END, 1)
    new_text = before + START + "\n" + table.rstrip() + "\n" + END + after
    README_PATH.write_text(new_text, encoding="utf-8")


def check_sync(rendered: str) -> int:
    readme = README_PATH.read_text(encoding="utf-8")
    generated = GENERATED_PATH.read_text(encoding="utf-8") if GENERATED_PATH.exists() else ""
    errors = []
    if rendered.strip() not in readme:
        errors.append("README.md is out of sync with skills/catalog.json")
    if generated.strip() != rendered.strip():
        errors.append("docs/generated/skills-table.md is out of sync with skills/catalog.json")
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    catalog = load_catalog()
    rendered = render_table(catalog)

    if args.check:
        return check_sync(rendered)

    GENERATED_PATH.write_text(rendered, encoding="utf-8")
    update_readme(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
